@startuml FarmacyContext
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
LAYOUT_TOP_DOWN
Person(customer, "Customer", "A customer of Farmacy Food")

Enterprise_Boundary(c0, "Farmacy Food System") {
    System(ecommerce, "Ecommerce System", "Allows customers to buy products online")
    System(smartFridge, "Smart Fridge", "Allows customers to buy products at kiosks")
    Person(kioskManager, "Kiosk manager", "")
    System(pos, "Toast POS", "Allows customer to pay for products at kiosks")
}

System(cheftec, "ChefTec", "Inventory Procurement")
System(payment, "Payment Engine", "Processes credit card payments on behalf of Farmacy Food.")
System(quickbook, "QuickBooks", "Accounting software for Farmacy food")

Rel_L(customer, ecommerce, "Discovers and Orders product using")
Rel_L(customer, smartFridge, "Purchases product at Coffeshop using")
Rel_L(customer, kioskManager, "Purchases product manually")
Rel_L(kioskManager, pos, "Enables payment using")

Rel_D(ecommerce, payment, "Process credit card using")
Rel_D(ecommerce, quickbook, "Generate invoice using")
Rel_D(pos, ecommerce, "Update inventory status using")
Rel_D(smartFridge, ecommerce, "Update inventory status using")



Rel_D(ecommerce, cheftec, "Update inventory status in")

@enduml
